version: "3.8"

services:
  user-service:
    container_name: user-service
    image: user-service-image:1.0.0
    build: ./user-service
    ports:
      - "8091:8091"
    environment:
      - DATABASE_URL=jdbc:postgresql://user-service-db:5432/user-service
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin123
    depends_on:
      - user-service-db
    volumes:
      - user-service-data:/var/lib/postgresql/data

  bank-service:
    container_name: bank-service
    image: bank-service-image:1.0.0
    build: ./bank-service
    ports:
      - "8092:8092"
    environment:
      - DATABASE_URL=jdbc:postgresql://bank-service-db:5433/bank-service
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin123
    depends_on:
      - bank-service-db
    volumes:
      - bank-service-data:/var/lib/postgresql/data

  messaging-service:
    container_name: messaging-service
    image: messaging-service-image:1.0.0
    build: ./messaging-service
    ports:
      - "8093:8093"

  user-service-db:
    container_name: user-service-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - user-service-data:/var/lib/postgresql/data

  bank-service-db:
    container_name: bank-service-db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bank-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - bank-service-data:/var/lib/postgresql/data

volumes:
  user-service-data:
  bank-service-data:
