#Application Configuration
server:
  port: 8092

spring:
  application:
    name: bank-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-service
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
appDescription: "Bank Service - Banco Digital"
appVersion: "1.0.0"